### ISSUE TITLE
开放平台报错 blivedm.clients.ws_base.InitError: init_room() failed

### ISSUE THREAD

**Issue by Ikaros-521** [xfgryujk/blivedm#50]
```
 2024-03-21 10:56:57 - e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\open_live.py[line:172] - ERROR: _start_game() failed:
Traceback (most recent call last):
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\open_live.py", line 157, in _start_game
    async with self._request_open_live(
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\aiohttp\client.py", line 493, in _request
    with timer:
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\aiohttp\helpers.py", line 725, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2024-03-21 10:56:57 - e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\ws_base.py[line:248] - ERROR: room=None _network_coroutine() finished with exception:
Traceback (most recent call last):
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\ws_base.py", line 243, in _network_coroutine_wrapper
    await self._network_coroutine()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\ws_base.py", line 264, in _network_coroutine
    await self._on_before_ws_connect(retry_count)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\open_live.py", line 271, in _on_before_ws_connect
    await super()._on_before_ws_connect(retry_count)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\blivedm\clients\ws_base.py", line 306, in _on_before_ws_connect
    raise InitError('init_room() failed')
blivedm.clients.ws_base.InitError: init_room() failed
```

**Comment by xfgryujk** [comment]
你反思一下自己网络有什么问题

**Comment by Ikaros-521** [comment]
> 你反思一下自己网络有什么问题

之前开着局部代理，局部代关了 还是一样的错误。

**Comment by Ikaros-521** [comment]
网络真的有问题，现在可以了，感谢大佬
![image](https://github.com/xfgryujk/blivedm/assets/40910637/95410cd1-2927-49d3-9cef-e2d382568295)
