### ISSUE TITLE
功能请求：使用 poetry/setup.py 进行打包

### ISSUE THREAD

**Issue by mokurin000** [xfgryujk/blivedm#57]
如题，目前在poetry添加 blivedm 作为依赖，
```bash
poetry add git+ssh://git@github.com:xfgryujk/blivedm.git
```

会报错：
```text
Error output:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "C:\Users\NEKO_P~1\AppData\Local\Temp\tmpv00wl79a\.venv\Lib\site-packages\build\__init__.py", line 199, in from_isolated_env
    return cls(
           ^^^^
  File "C:\Users\NEKO_P~1\AppData\Local\Temp\tmpv00wl79a\.venv\Lib\site-packages\build\__init__.py", line 174, in __init__
    _validate_source_directory(source_dir)
  File "C:\Users\NEKO_P~1\AppData\Local\Temp\tmpv00wl79a\.venv\Lib\site-packages\build\__init__.py", line 77, in _validate_source_directory 
    raise BuildException(msg)
build._exceptions.BuildException: Source C:/Users/neko_poly000/AppData/Local/pypoetry/Cache/virtualenvs/blive-qq-forward--M0WCSHV-py3.12/src/blivedm does not appear to be a Python project: no pyproject.toml or setup.py
```

**Comment by mokurin000** [comment]
我还以为 pypi 不需要打包就可以上传... 原来是 #25 打包和上传了 我还纳闷为什么id不一样
我打包也就为了方便自己仓库中 poetry管理 & 使用贵仓库作为依赖
既然贵作者不同意打包成合规的“python project”，我也没辙

**Comment by mokurin000** [comment]
emmm 因为 “pyproject.toml” 把自己绕晕了
现在才知道 `tool.poetry.*` 是 PEP621前的遗留字段
最新的分发标准是 [`pyproject.toml`](https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec)
